CREATE DATABASE IF NOT EXISTS Ripple;
USE Ripple;
CREATE TABLE IF NOT EXISTS Records(
	rid 		INTEGER AUTO_INCREMENT PRIMARY KEY,
	t   		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	source 		VARCHAR(12) NOT NULL,
	sequence 	INTEGER NOT NULL,
	estage		INTEGER NOT NULL,
	hops		INTEGER NOT NULL,
	hrate		INTEGER NOT NULL,
	sp02		INTEGER NOT NULL,
	resp		INTEGER NOT NULL,
	temp		INTEGER NOT NULL,
	status		INTEGER NOT NULL
);

CREATE USER 'ripple'@'localhost' IDENTIFIED BY 'ripplepass';
GRANT ALL PRIVILEGES ON Ripple.* TO 'ripple'@'localhost';
